Metode Analytical Hierarchy Process (AHP) merupakan suatu pendekatan yang digunakan untuk mengambil keputusan dengan mempertimbangkan berbagai kriteria dan alternatif secara hierarki. Metode ini dikembangkan oleh Thomas L.

Saaty pada tahun 1970-an dan telah banyak diterapkan dalam berbagai bidang, seperti manajemen, perencanaan, dan pengambilan keputusan. AHP membantu mengurai kompleksitas suatu masalah dengan merinci elemen-elemen keputusan menjadi tingkatan yang lebih kecil, sehingga memudahkan analisis dan penilaian.

Dengan memanfaatkan prinsip perbandingan berpasangan, AHP memungkinkan pemangku kepentingan untuk memberikan bobot atau nilai relatif pada setiap kriteria dan alternatif.